/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_manage_system;

import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class ListOfStudents extends javax.swing.JFrame {
    
//    String constr ="jdbc:sqlserver://localhost;InstanceName=MSSQLSERVER;databaseName=SchoolManagementSystem;user=sa;password=fabulous";

    Connection con = null;
    PreparedStatement ps = null;
    
    /**
     * Creates new form ListOfStudents
     */
    public ListOfStudents() {
        initComponents();
        StudentSignIn in = new StudentSignIn();
        StudentSignIn.txtEmail.setText(null);
        StudentSignIn.txtpassword.setText(null);
        StudentSignIn.txtcpassword.setText(null);
       
        //StudentProfile
        StudentProfile file = new StudentProfile();
        StudentProfile.lblname.setText(null);
        StudentProfile.lblaccount.setText(null);
        StudentProfile.lblbiology.setText(null);
        StudentProfile.lblcommerce.setText(null);
        StudentProfile.lblecons.setText(null);
        StudentProfile.lblenglish.setText(null);
        StudentProfile.lblfurther.setText(null);
        StudentProfile.lblgeography.setText(null);
        StudentProfile.lblphysics.setText(null);
        StudentProfile.lblmaths.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pthomas = new javax.swing.JPanel();
        lblthomas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pthomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pthomasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pthomasMousePressed(evt);
            }
        });

        lblthomas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblthomas.setText("Thomas    Fabulous");
        lblthomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblthomasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pthomasLayout = new javax.swing.GroupLayout(pthomas);
        pthomas.setLayout(pthomasLayout);
        pthomasLayout.setHorizontalGroup(
            pthomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pthomasLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblthomas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        pthomasLayout.setVerticalGroup(
            pthomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblthomas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pthomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pthomasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pthomasMousePressed

        try {
            con = dbConnect.getConnection();
            ps = con.prepareStatement("Select email, password, cpassword, name from student_signup where email = ?");
            ps.setString(1, StudentSignIn.txtEmail.getText());
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                if (StudentSignIn.txtEmail.getText().equals(rs.getString("email"))) {
                    StudentSignIn.txtEmail.setText(rs.getString("email"));
                    StudentSignIn.txtpassword.setText(rs.getString("password"));
                    StudentSignIn.txtcpassword.setText(rs.getString("password"));
                    
                    JOptionPane.showMessageDialog(this, "Welcome " + rs.getString("name"));
                    new StudentProfile().show();
                    this.dispose();
                }
                
                else {
                    JOptionPane.showMessageDialog(this, "You are not " + rs.getString("name"));
                }
            }
        }
        catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_pthomasMousePressed

    private void lblthomasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthomasMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lblthomasMousePressed

    private void pthomasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pthomasMouseClicked
        // TODO add your handling code here:
        try {
            con = dbConnect.getConnection();
            ps = con.prepareStatement("Select email, password, cpassword, name from student_signup where email = ?");
            ps.setString(1, StudentSignIn.txtEmail.getText());
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                if (StudentSignIn.txtEmail.getText().equals(rs.getString("email"))) {
                    StudentSignIn.txtEmail.setText(rs.getString("email"));
                    StudentSignIn.txtpassword.setText(rs.getString("password"));
                    StudentSignIn.txtcpassword.setText(rs.getString("password"));
                    
                    JOptionPane.showMessageDialog(this, "Welcome " + rs.getString("name"));
                    
                    new StudentProfile().show();
                    this.dispose();
                }
                
                else {
                    JOptionPane.showMessageDialog(this, "You are not " + rs.getString("name"));
                }
            }
        }
        catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_pthomasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblthomas;
    private javax.swing.JPanel pthomas;
    // End of variables declaration//GEN-END:variables
}
