/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_manage_system;

/**
 *
 * @author hp
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelparent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelteachers = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelnew = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelstudent = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paneladmin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Excel Int'l Schools");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 380, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(To be great is our priority)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("For Both Boys and Girls");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 110));

        panelparent.setBackground(new java.awt.Color(255, 255, 255));
        panelparent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelparent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelparentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelparentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelparentMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Parent");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Family_80px.png"))); // NOI18N

        javax.swing.GroupLayout panelparentLayout = new javax.swing.GroupLayout(panelparent);
        panelparent.setLayout(panelparentLayout);
        panelparentLayout.setHorizontalGroup(
            panelparentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelparentLayout.createSequentialGroup()
                .addGroup(panelparentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelparentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(panelparentLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelparentLayout.setVerticalGroup(
            panelparentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelparentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(19, 19, 19))
        );

        jPanel1.add(panelparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, 120));

        panelteachers.setBackground(new java.awt.Color(255, 255, 255));
        panelteachers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelteachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelteachersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelteachersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelteachersMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Classroom_80px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Teachers");

        javax.swing.GroupLayout panelteachersLayout = new javax.swing.GroupLayout(panelteachers);
        panelteachers.setLayout(panelteachersLayout);
        panelteachersLayout.setHorizontalGroup(
            panelteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelteachersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelteachersLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addComponent(jLabel7))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelteachersLayout.setVerticalGroup(
            panelteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelteachersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelteachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 120, 120));

        panelnew.setBackground(new java.awt.Color(255, 255, 255));
        panelnew.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelnewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelnewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelnewMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("New Student");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Add_User_Male_80px.png"))); // NOI18N

        javax.swing.GroupLayout panelnewLayout = new javax.swing.GroupLayout(panelnew);
        panelnew.setLayout(panelnewLayout);
        panelnewLayout.setHorizontalGroup(
            panelnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnewLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(panelnewLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelnewLayout.setVerticalGroup(
            panelnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnewLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(33, 33, 33))
        );

        jPanel1.add(panelnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 120, 120));

        panelstudent.setBackground(new java.awt.Color(255, 255, 255));
        panelstudent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelstudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelstudentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelstudentMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Student");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Students_80px.png"))); // NOI18N

        javax.swing.GroupLayout panelstudentLayout = new javax.swing.GroupLayout(panelstudent);
        panelstudent.setLayout(panelstudentLayout);
        panelstudentLayout.setHorizontalGroup(
            panelstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelstudentLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelstudentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelstudentLayout.setVerticalGroup(
            panelstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelstudentLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        jPanel1.add(panelstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 120, 120));

        paneladmin.setBackground(new java.awt.Color(255, 255, 255));
        paneladmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paneladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneladminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneladminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneladminMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Admin");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_School_Director_80px.png"))); // NOI18N

        javax.swing.GroupLayout paneladminLayout = new javax.swing.GroupLayout(paneladmin);
        paneladmin.setLayout(paneladminLayout);
        paneladminLayout.setHorizontalGroup(
            paneladminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladminLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(paneladminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladminLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladminLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35))))
        );
        paneladminLayout.setVerticalGroup(
            paneladminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladminLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(16, 16, 16))
        );

        jPanel1.add(paneladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelparentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelparentMouseEntered
        panelparent.setBackground(new java.awt.Color(204,153,255));
    }//GEN-LAST:event_panelparentMouseEntered

    private void panelparentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelparentMouseExited
        panelparent.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_panelparentMouseExited

    private void panelteachersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelteachersMouseEntered
        panelteachers.setBackground(new java.awt.Color(204,153,255));
    }//GEN-LAST:event_panelteachersMouseEntered

    private void panelteachersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelteachersMouseExited
        panelteachers.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_panelteachersMouseExited

    private void panelstudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelstudentMouseEntered
        panelstudent.setBackground(new java.awt.Color(204,153,255));
    }//GEN-LAST:event_panelstudentMouseEntered

    private void panelstudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelstudentMouseExited
        panelstudent.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_panelstudentMouseExited

    private void paneladminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladminMouseEntered
        paneladmin.setBackground(new java.awt.Color(204,153,255));
    }//GEN-LAST:event_paneladminMouseEntered

    private void paneladminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladminMouseExited
        paneladmin.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_paneladminMouseExited

    private void panelnewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelnewMouseEntered
        panelnew.setBackground(new java.awt.Color(204,153,255));
    }//GEN-LAST:event_panelnewMouseEntered

    private void panelnewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelnewMouseExited
        panelnew.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_panelnewMouseExited

    private void panelparentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelparentMousePressed
        new ParentSignIn().show();
        this.dispose();
    }//GEN-LAST:event_panelparentMousePressed

    private void panelteachersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelteachersMousePressed
        
    }//GEN-LAST:event_panelteachersMousePressed

    private void panelnewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelnewMousePressed
        new StudentSignUp().show();
        this.dispose();
    }//GEN-LAST:event_panelnewMousePressed

    private void panelstudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelstudentMousePressed
        new StudentSignIn().show();
        this.dispose();
    }//GEN-LAST:event_panelstudentMousePressed

    private void paneladminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladminMousePressed
        new AdminSignIn().show();
        this.dispose();
    }//GEN-LAST:event_paneladminMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel paneladmin;
    private javax.swing.JPanel panelnew;
    private javax.swing.JPanel panelparent;
    private javax.swing.JPanel panelstudent;
    private javax.swing.JPanel panelteachers;
    // End of variables declaration//GEN-END:variables
}
