/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_manage_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class ParentSignUp extends javax.swing.JFrame {

    String constr ="jdbc:sqlserver://localhost;InstanceName=MSSQLSERVER;databaseName=SchoolManagementSystem;user=sa;password=fabulous";
    /**
     * Creates new form ParentSignIn
     */
    public ParentSignUp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtsurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        lblreset = new javax.swing.JLabel();
        lblsubmit = new javax.swing.JLabel();
        lblsignup1 = new javax.swing.JLabel();
        lblsignin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setText("Sign-Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Provide your details....");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 210, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Email-Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Surname");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Undo_20px.png"))); // NOI18N
        jLabel7.setToolTipText("Go back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtname.setToolTipText("Enter Email-Address");
        txtname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 237, 33));

        txtsurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtsurname.setToolTipText("Enter Email-Address");
        txtsurname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtsurname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 237, 33));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setToolTipText("Enter Email-Address");
        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 237, 33));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 237, 35));

        lblreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Reset_15px_1.png"))); // NOI18N
        lblreset.setText("Reset");
        lblreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblresetMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblresetMousePressed(evt);
            }
        });
        jPanel1.add(lblreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 82, 30));

        lblsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Submit_for_Approval_15px.png"))); // NOI18N
        lblsubmit.setText("Submit");
        lblsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsubmitMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblsubmitMousePressed(evt);
            }
        });
        jPanel1.add(lblsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, 30));

        lblsignup1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblsignup1.setText("Already have an account?");
        jPanel1.add(lblsignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        lblsignin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblsignin.setText("Sign-In instead");
        lblsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblsigninMousePressed(evt);
            }
        });
        jPanel1.add(lblsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        new ParentSignIn().show();
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed

    private void lblsubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsubmitMousePressed
        try{
            String str = "Insert into Parents values(?,?,?,?)";
            // String sts = "Select FirstName";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            try(Connection con = DriverManager.getConnection(constr);
                PreparedStatement smt = con.prepareStatement(str);)
            {
                smt.setString(1, txtname.getText());
                smt.setString(2, txtsurname.getText());
                smt.setString(3, txtEmail.getText());
                smt.setString(4, txtpassword.getText());

                int count = smt.executeUpdate();
                JOptionPane.showMessageDialog(this, count+"Concratulations \nRegistration is successful");
                txtname.setText("");
                txtsurname.setText("");
                txtEmail.setText("");
                txtpassword.setText("");

                try
                {
                    String stg = "Select FirstName from Parents where FirstName = ?";
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    try(Connection conn = DriverManager.getConnection(constr);
                        PreparedStatement stmt = conn.prepareStatement(stg);)
                    {
                        stmt.setString(1, txtname.getText());
                        ResultSet rs = smt.executeQuery();
                        while(rs.next())
                        {
                            txtname.setText(rs.getString("FirstName"));
                            if(txtname.getText().equals(rs.getString("FirstName"))){
                                JOptionPane.showMessageDialog(this, "Welcome"+" "+rs.getString("FirstName"));
                                new ParentSignIn().show();
                                this.dispose();
                            }
                            else{
                                JOptionPane.showMessageDialog(this, "Check your details and try again.");
                            }
                        }
                    }
                }
                catch(Exception ex){
                    System.out.println(ex);
                }
            }
        }
        catch(Exception ex){
            System.out.println(ex);
        }

        //int sel = JOptionPane.showConfirmDialog(this,"You have booked your room");
        //        if(JOptionPane == ){
            //            home ho = new home();
            //        ho.show();
            //        }
    }//GEN-LAST:event_lblsubmitMousePressed

    private void lblsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsubmitMouseEntered
        lblsubmit.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_lblsubmitMouseEntered

    private void lblresetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblresetMousePressed
        txtsurname.setText(null);
        txtname.setText(null);
        txtEmail.setText(null);
        txtpassword.setText(null);
    }//GEN-LAST:event_lblresetMousePressed

    private void lblresetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblresetMouseExited
        lblsubmit.setBackground(new java.awt.Color(204,153,255));
    }//GEN-LAST:event_lblresetMouseExited

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void lblsigninMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsigninMousePressed
        new ParentSignIn().show();
        this.dispose();
    }//GEN-LAST:event_lblsigninMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblreset;
    private javax.swing.JLabel lblsignin;
    private javax.swing.JLabel lblsignup1;
    private javax.swing.JLabel lblsubmit;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtsurname;
    // End of variables declaration//GEN-END:variables
}
