/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_manage_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hp
 */
public class StudentProfile extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement ps = null;
    /**
     * Creates new form StudentProfile
     */
    public StudentProfile() {
        initComponents();
        
        try {
            con = dbConnect.getConnection();
            ps = con.prepareStatement("select ss.name,ss.surname,ss.email,ss.pnumber,ss.country,s.math,s.english,s.account,s.economics,s.commerce,s.biology,s.furthermath,s.geography,s.physics from school.student_signup ss CROSS JOIN school.subjects s where ss.email = ?");
//            ps = con.prepareStatement("select Name,English,Maths,Geography,FurthMaths,Accounting,Commerce,Economics,Biology,Physics from Student where Name = ?");
            
            ps.setString(1, lblname.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                lblname.setText(rs.getString("name"));
                lblaccount.setText(rs.getString("account"));
                lblbiology.setText(rs.getString("biology"));
                lblcommerce.setText(rs.getString("commerce"));
                lblecons.setText(rs.getString("economics"));
                lblenglish.setText(rs.getString("english"));
                lblfurther.setText(rs.getString("furthermath"));
                lblgeography.setText(rs.getString("geography"));
                lblmaths.setText(rs.getString("maths"));
                lblphysics.setText(rs.getString("physics"));
                lblemail.setText(rs.getString("email"));
                lblnum.setText(rs.getString("pnumber"));
                lblcountry.setText(rs.getString("country"));
            }
        }
        
        catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblenglish = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblphysics = new javax.swing.JLabel();
        lblmaths = new javax.swing.JLabel();
        lblcountry = new javax.swing.JLabel();
        lblaccount = new javax.swing.JLabel();
        lblecons = new javax.swing.JLabel();
        lblcommerce = new javax.swing.JLabel();
        lblbiology = new javax.swing.JLabel();
        lblgeography = new javax.swing.JLabel();
        lblfurther = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblnum = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 255), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_School_Director_80px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 80, 80));

        lblenglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblenglish.setText("English Language");
        jPanel1.add(lblenglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, 30));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblname.setText("Name");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Personal Information");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, 30));

        lblphysics.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblphysics.setText("Phys");
        jPanel1.add(lblphysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 160, 30));

        lblmaths.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmaths.setText("Math");
        jPanel1.add(lblmaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, 30));

        lblcountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcountry.setText("Country");
        jPanel1.add(lblcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 220, 30));

        lblaccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblaccount.setText("Account");
        jPanel1.add(lblaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 160, 30));

        lblecons.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblecons.setText("Econs");
        jPanel1.add(lblecons, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 160, 30));

        lblcommerce.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcommerce.setText("Comm");
        jPanel1.add(lblcommerce, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 160, 30));

        lblbiology.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblbiology.setText("Bio");
        jPanel1.add(lblbiology, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 160, 30));

        lblgeography.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblgeography.setText("Geo");
        jPanel1.add(lblgeography, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 160, 30));

        lblfurther.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblfurther.setText("Further");
        jPanel1.add(lblfurther, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Subjects Offered");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Contacts");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 90, 30));

        lblemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblemail.setText("Email-Address");
        jPanel1.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 220, 30));

        lblnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblnum.setText("Phone Number");
        jPanel1.add(lblnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 220, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Undo_20px.png"))); // NOI18N
        jLabel13.setToolTipText("Go back");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        new Main().show();
        this.dispose();
    }//GEN-LAST:event_jLabel13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblaccount;
    public static javax.swing.JLabel lblbiology;
    public static javax.swing.JLabel lblcommerce;
    public static javax.swing.JLabel lblcountry;
    public static javax.swing.JLabel lblecons;
    public static javax.swing.JLabel lblemail;
    public static javax.swing.JLabel lblenglish;
    public static javax.swing.JLabel lblfurther;
    public static javax.swing.JLabel lblgeography;
    public static javax.swing.JLabel lblmaths;
    public static javax.swing.JLabel lblname;
    public static javax.swing.JLabel lblnum;
    public static javax.swing.JLabel lblphysics;
    // End of variables declaration//GEN-END:variables
}
