/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_manage_system;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import static school_manage_system.StudentProfile.lblaccount;
//import static school_manage_system.StudentProfile.lblbiology;
//import static school_manage_system.StudentProfile.lblcommerce;
//import static school_manage_system.StudentProfile.lblcountry;
//import static school_manage_system.StudentProfile.lblecons;
//import static school_manage_system.StudentProfile.lblemail;
//import static school_manage_system.StudentProfile.lblenglish;
//import static school_manage_system.StudentProfile.lblfurther;
//import static school_manage_system.StudentProfile.lblgeography;
//import static school_manage_system.StudentProfile.lblmaths;
//import static school_manage_system.StudentProfile.lblname;
//import static school_manage_system.StudentProfile.lblnum;
//import static school_manage_system.StudentProfile.lblphysics;

/**
 *
 * @author hp
 */
public class StudentSignIn extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement ps = null;

//    String constr ="jdbc:sqlserver://localhost;InstanceName=MSSQLSERVER;databaseName=SchoolManagementSystem;user=sa;password=fabulous";
    /**
     * Creates new form StudentSignIn
     */
    public StudentSignIn() {
        initComponents();
//        setLocation(800, 100);
        setLocationRelativeTo(null);
        setResizable(false);
        
//        ListOfStudents list = new ListOfStudents();
        
        StudentProfile file = new StudentProfile();
        StudentProfile.lblname.setText(null);
        StudentProfile.lblaccount.setText(null);
        StudentProfile.lblbiology.setText(null);
        StudentProfile.lblcommerce.setText(null);
        StudentProfile.lblecons.setText(null);
        StudentProfile.lblenglish.setText(null);
        StudentProfile.lblfurther.setText(null);
        StudentProfile.lblgeography.setText(null);
        StudentProfile.lblphysics.setText(null);
        StudentProfile.lblmaths.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtcpassword = new javax.swing.JPasswordField();
        chkshowpass = new javax.swing.JCheckBox();
        btnreset = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setText("Sign-In");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Provide your details....");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Confirm Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 220, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Email-Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, 40));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setToolTipText("Enter Email-Address");
        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 216, 33));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 216, 35));

        txtcpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtcpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 216, 35));

        chkshowpass.setText("Show password");
        chkshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkshowpassActionPerformed(evt);
            }
        });
        jPanel1.add(chkshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnresetMousePressed(evt);
            }
        });
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 103, -1));

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Undo_20px.png"))); // NOI18N
        jLabel7.setToolTipText("Go back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetMousePressed
        txtEmail.setText(null);
        txtpassword.setText(null);
        txtcpassword.setText(null);
        chkshowpass.setText(null);
    }//GEN-LAST:event_btnresetMousePressed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed


        try {
            con = dbConnect.getConnection();
            ps = con.prepareStatement("Select email, password, cpassword, name from student_signup where email = ?");
            ps.setString(1, txtEmail.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                
                if (txtEmail.getText().equals("")
                        && txtpassword.getText().equals("")
                        && txtcpassword.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "field can;t be empty");
                }
           
                else {
                txtEmail.setText(rs.getString("email"));
                txtpassword.setText(rs.getString("password"));
                txtcpassword.setText(rs.getString("password"));

                JOptionPane.showMessageDialog(this, "Login is successful");

                if (txtEmail.getText().equals(rs.getString("email"))
                        && txtpassword.getText().equals(rs.getString("password"))
                        && txtcpassword.getText().equals(rs.getString("password"))) {
                    JOptionPane.showMessageDialog(this, "Welcome" + "   " + rs.getString("name"));
                    
                    new StudentProfile().show();
                    this.dispose();
                }
            }
            }
            
            try {
            con = dbConnect.getConnection();
//            ps = con.prepareStatement("select ss.name,ss.surname,ss.email,ss.pnumber,ss.country,s.math,s.english,s.account,s.economics,s.commerce,s.biology,s.furthermath,s.geography,s.physics from school.student_signup ss CROSS JOIN school.subjects s where ss.email = ?");
//            ps = con.prepareStatement("select Name,English,Maths,Geography,FurthMaths,Accounting,Commerce,Economics,Biology,Physics from Student where Name = ?");
              ps = con.prepareStatement("select name, email, pnumber, country from student_signup where name = ?");
            
            ps.setString(1, StudentProfile.lblname.getText());
            ResultSet rs1 = ps.executeQuery();
            while (rs.next()) {
                StudentProfile.lblname.setText(rs1.getString("name"));
//                StudentProfile.lblaccount.setText(rs1.getString("account"));
//                StudentProfile.lblbiology.setText(rs1.getString("biology"));
//                StudentProfile.lblcommerce.setText(rs1.getString("commerce"));
//                StudentProfile.lblecons.setText(rs1.getString("economics"));
//                StudentProfile.lblenglish.setText(rs1.getString("english"));
//                StudentProfile.lblfurther.setText(rs1.getString("furthermath"));
//                StudentProfile.lblgeography.setText(rs1.getString("geography"));
//                StudentProfile.lblmaths.setText(rs1.getString("maths"));
//                StudentProfile.lblphysics.setText(rs1.getString("physics"));
                StudentProfile.lblemail.setText(rs1.getString("email"));
                StudentProfile.lblnum.setText(rs1.getString("pnumber"));
                StudentProfile.lblcountry.setText(rs1.getString("country"));
            }
        }
        
        catch (SQLException exc) {
            System.out.println(exc);
        }
    

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnsubmitActionPerformed

    private void chkshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkshowpassActionPerformed
        try {
            ps = con.prepareStatement("select password from student_signup where password = ?");

            ps.setString(1, txtpassword.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                txtpassword.setText(rs.getString("password"));
                txtcpassword.setText(rs.getString("password"));
                if (txtpassword.getText().equals(rs.getString("password"))) {
                    chkshowpass.setText(txtpassword.getText());
                    txtpassword.setVisible(true);
                }
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_chkshowpassActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        new Main().show();
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JCheckBox chkshowpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JPasswordField txtcpassword;
    public static javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
