/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_manage_system;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class StudentSignUp extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement ps = null;

//    String constr = "jdbc:sqlserver://localhost;InstanceName=MSSQLSERVER;databaseName=SchoolManagementSystem;user=sa;password=fabulous";

    public StudentSignUp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtsurname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtnationality = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtemail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnreset = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcmbstate = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtparentname = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtphone = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtcpassword = new javax.swing.JPasswordField();
        txtpassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        noagree = new javax.swing.JCheckBox();
        agree = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setText("Sign-Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Provide information");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email-Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 90, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Surname");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtname.setToolTipText("Enter Email-Address");
        txtname.setBorder(null);
        txtname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 220, 30));

        jSeparator1.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 11));

        txtsurname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsurname.setToolTipText("Enter Email-Address");
        txtsurname.setBorder(null);
        txtsurname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, 30));

        jSeparator2.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, 11));

        txtnationality.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnationality.setToolTipText("Enter Email-Address");
        txtnationality.setBorder(null);
        txtnationality.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, 30));

        jSeparator3.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator3.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, 11));

        jSeparator4.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator4.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 220, 11));

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtemail.setToolTipText("Enter Email-Address");
        txtemail.setBorder(null);
        txtemail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 220, 30));

        jSeparator5.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator5.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 200, 11));

        jSeparator6.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator6.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 220, 11));

        btnreset.setBackground(new java.awt.Color(204, 153, 255));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 103, -1));

        btnsubmit.setBackground(new java.awt.Color(204, 153, 255));
        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Nationality");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 100, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("State of Origin");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 20));

        jcmbstate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcmbstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------Nigerians only-------", "Abia", "Anambra", "Bauchi", "Delta", "Ebonyi", "Benin", "Edo", "Abuja", "Lagos", "Osun", "Cross-River", "Enugu", "Oweri", "Ogun", "Kwara", "Nasrawa", "Yobe", "Katsina", "Oyo" }));
        jPanel1.add(jcmbstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Parent's Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 140, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Phone Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 140, -1));

        txtparentname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtparentname.setToolTipText("Enter Email-Address");
        txtparentname.setBorder(null);
        txtparentname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtparentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 220, 30));

        jSeparator7.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator7.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 220, 11));

        txtphone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtphone.setToolTipText("Enter Email-Address");
        txtphone.setBorder(null);
        txtphone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 220, 30));

        jSeparator8.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator8.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 220, 11));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Confirm Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, 20));

        jSeparator9.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator9.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 220, 11));

        txtcpassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcpassword.setText("jPasswordField1");
        txtcpassword.setBorder(null);
        jPanel1.add(txtcpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 220, 30));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtpassword.setText("jPasswordField1");
        txtpassword.setBorder(null);
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 220, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("          ");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 360, 150));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Terms  and  Conditions");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 150, 20));

        jSeparator10.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator10.setForeground(new java.awt.Color(204, 153, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 220, 11));

        noagree.setText("I do not agree with the terms and conditions of the school");
        jPanel1.add(noagree, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        agree.setText("I agree with the terms and contions of the school");
        jPanel1.add(agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Undo_20px.png"))); // NOI18N
        jLabel13.setToolTipText("Go back");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtname.setText(null);
        txtsurname.setText(null);
        txtnationality.setText(null);
        jcmbstate.setSelectedIndex(0);
        txtemail.setText(null);
        txtpassword.setText(null);
        txtcpassword.setText(null);
        txtparentname.setText(null);
        txtphone.setText(null);
        agree.setSelected(false);
        noagree.setSelected(false);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed

        try {
            con = dbConnect.getConnection();
            ps = con.prepareStatement("insert into student_signup values(?,?,?,?,?,?,?,?,?)");
            
            ps.setString(1, txtname.getText());
            ps.setString(2, txtsurname.getText());
            ps.setString(3, txtnationality.getText());
            ps.setString(4, jcmbstate.getSelectedItem().toString());
            ps.setString(5, txtemail.getText());
            ps.setString(6, txtpassword.getText());
            ps.setString(7, txtcpassword.getText());
            ps.setString(8, txtparentname.getText());
            ps.setString(9, txtphone.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Congratulations \nRegistration is successful");
            txtname.setText("");
            txtsurname.setText("");
            txtnationality.setText("");
            jcmbstate.setSelectedItem("");
            txtemail.setText("");
            txtpassword.setText("");
            txtcpassword.setText("");
            txtparentname.setText("");
            txtphone.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(StudentSignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        new StudentSignIn().show();
        this.dispose();
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        new Main().show();
        this.dispose();
    }//GEN-LAST:event_jLabel13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agree;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcmbstate;
    private javax.swing.JCheckBox noagree;
    private javax.swing.JPasswordField txtcpassword;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtparentname;
    public static javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsurname;
    // End of variables declaration//GEN-END:variables

}
