/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_manage_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static school_manage_system.PrintOut.txtPrintout;
import static school_manage_system.StudentSignUp.txtpassword;

/**
 *
 * @author hp
 */
public class StudentResult_teacher extends javax.swing.JFrame {

//    String constr ="jdbc:sqlserver://localhost;InstanceName=DESKTOP-O8DRRCK;databaseName=SchoolManagementSystem;user=Thomas;password=fabulous";
    Connection con = null;
    PreparedStatement ps = null;

    /**
     * Creates new form StudentResult
     */
    public StudentResult_teacher() {
        initComponents();
        setLocationRelativeTo(null);

//        Overriding Method StudentResult();
        PrintOut prin = new PrintOut();
        txtPrintout.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmaths = new javax.swing.JTextField();
        txtaccount = new javax.swing.JTextField();
        txtenglish = new javax.swing.JTextField();
        txtcommerce = new javax.swing.JTextField();
        txtbiology = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfurther = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtphysics = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtgeography = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtgrades = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtecons = new javax.swing.JTextField();
        txtaverage = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTranscript = new javax.swing.JTextArea();
        jSeparator15 = new javax.swing.JSeparator();
        btnReset = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        Sid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtscore = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 255), 3), "Student Result", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 33))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Commerce");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Student ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mathematics");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Accounting");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("English");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Biology");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setToolTipText("Enter name");
        txtname.setBorder(null);
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, 30));

        txtmaths.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmaths.setToolTipText("");
        jPanel1.add(txtmaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 30));

        txtaccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtaccount.setToolTipText("");
        jPanel1.add(txtaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, 30));

        txtenglish.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtenglish.setToolTipText("");
        jPanel1.add(txtenglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, 30));

        txtcommerce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcommerce.setToolTipText("");
        jPanel1.add(txtcommerce, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 160, 30));

        txtbiology.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbiology.setToolTipText("");
        jPanel1.add(txtbiology, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Further Maths");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 130, -1));

        txtfurther.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfurther.setToolTipText("");
        jPanel1.add(txtfurther, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Physics");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 70, -1));

        txtphysics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtphysics.setToolTipText("");
        jPanel1.add(txtphysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Geography");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 100, -1));

        txtgeography.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtgeography.setToolTipText("");
        jPanel1.add(txtgeography, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 160, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total Score");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txtgrades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtgrades.setToolTipText("");
        jPanel1.add(txtgrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 160, 30));

        jSeparator12.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 300, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Economics");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Grades");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 70, -1));

        txtecons.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtecons.setToolTipText("");
        jPanel1.add(txtecons, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 160, 30));

        txtaverage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtaverage.setToolTipText("");
        jPanel1.add(txtaverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 160, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Average");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 80, -1));

        jSeparator14.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, 10));

        txtTranscript.setEditable(false);
        txtTranscript.setColumns(20);
        txtTranscript.setRows(5);
        txtTranscript.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 255), 2, true), "Result PrintOut", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(txtTranscript);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 320, 330));

        jSeparator15.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 10));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 100, -1));

        btnTranscript.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });
        jPanel1.add(btnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 130, -1));

        btnGenerate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerate.setText("Insert");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 120, -1));

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 120, -1));

        Sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SidActionPerformed(evt);
            }
        });
        jPanel1.add(Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_manage_system/Icons/icons8_Undo_20px.png"))); // NOI18N
        jLabel15.setToolTipText("Go back");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 20));

        txtscore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtscore.setToolTipText("");
        jPanel1.add(txtscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtname.setText(null);
        txtmaths.setText(null);
        txtenglish.setText(null);
        txtbiology.setText(null);
        txtphysics.setText(null);
        txtecons.setText(null);
        txtgeography.setText(null);
        txtaccount.setText(null);
        txtcommerce.setText(null);
        txtfurther.setText(null);
        Sid.setText(null);
        txtTranscript.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        txtTranscript.getText();
        txtTranscript.append("\n                         Excel International School\n"
                + "                         (To be great is our Priority)"
                + "\n    Student Name :    \t" + txtname.getText()
                + "\n    Student ID :    \t\t " + Sid.getText()
                + "\n __________________________________________"
                + "\n\tSubjects Offered"
                + "\n    Mathematics :   \t " + txtmaths.getText()
                + "\n    Accounting :   \t\t " + txtaccount.getText()
                + "\n    English Language :   \t " + txtenglish.getText()
                + "\n    Commerce :   \t " + txtcommerce.getText()
                + "\n    Economics :   \t " + txtecons.getText()
                + "\n    Further Maths :   \t " + txtfurther.getText()
                + "\n    Physics :   \t\t " + txtphysics.getText()
                + "\n    Geography :   \t\t " + txtgeography.getText()
                + "\n    Biology :   \t\t " + txtbiology.getText()
                + "\n    Average Score :   \t\t " + txtaverage.getText()
                + "\n    Total Score :   \t\t " + txtgrades.getText());
    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed

        try {
            con = dbConnect.getConnection();
            ps = con.prepareStatement("insert into student values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            ps.setString(1, txtname.getText());
            ps.setString(2, Sid.getText());
            ps.setString(3, txtmaths.getText());
            ps.setString(4, txtenglish.getText());
            ps.setString(5, txtaccount.getText());
            ps.setString(6, txtcommerce.getText());
            ps.setString(7, txtphysics.getText());
            ps.setString(8, txtbiology.getText());
            ps.setString(9, txtecons.getText());
            ps.setString(10, txtgeography.getText());
            ps.setString(11, txtfurther.getText());
            ps.setString(12, txtgrades.getText());
            ps.setString(13, txtscore.getText());
            ps.setString(14, txtaverage.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Congratulations \nRecords inserted successfully");
            txtname.setText("");
            Sid.setText("");
            txtmaths.setText("");
            txtenglish.setText("");
            txtaccount.setText("");
            txtcommerce.setText("");
            txtphysics.setText("");
            txtbiology.setText("");
            txtecons.setText("");
            txtgeography.setText("");
            txtfurther.setText("");
            txtgrades.setText("");
            txtscore.setText("");
            txtaverage.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(StudentSignUp.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed

    }//GEN-LAST:event_btnprintActionPerformed

    private void SidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SidActionPerformed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        new Main().show();
        this.dispose();
    }//GEN-LAST:event_jLabel15MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResult_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResult_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResult_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResult_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResult_teacher().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Sid;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    public static javax.swing.JTextArea txtTranscript;
    private javax.swing.JTextField txtaccount;
    private javax.swing.JTextField txtaverage;
    private javax.swing.JTextField txtbiology;
    private javax.swing.JTextField txtcommerce;
    private javax.swing.JTextField txtecons;
    private javax.swing.JTextField txtenglish;
    private javax.swing.JTextField txtfurther;
    private javax.swing.JTextField txtgeography;
    private javax.swing.JTextField txtgrades;
    private javax.swing.JTextField txtmaths;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphysics;
    private javax.swing.JTextField txtscore;
    // End of variables declaration//GEN-END:variables
}
